//========================================================================================
// AthenaK: astrophysical fluid dynamics & numerical relativity code
// Copyright(C) 2020 James M. Stone <jmstone@ias.edu> and the Athena code team
// Licensed under the 3-clause BSD License (the "LICENSE")
//========================================================================================
//! \file z4c_spectre_bbh.cpp
//  \brief Problem generator for binary black hole initial data generated by
//  the SpECTRE code (https://spectre-code.org).

#include <algorithm>
#include <cmath>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <Kokkos_Timer.hpp>

#include "athena.hpp"
#include "coordinates/cell_locations.hpp"
#include "coordinates/adm.hpp"
#include "globals.hpp"
#include "mesh/mesh.hpp"
#include "parameter_input.hpp"
#include "z4c/z4c.hpp"
#include "z4c/z4c_amr.hpp"

#include <spectre/Exporter.hpp>

// Forward declarations
struct BHPosition {
  double M;
  double x;
  double y;
  double z;
};
void LoadSpectreInitialData(MeshBlockPack *pmbp, const std::vector<BHPosition> &bh_positions,
                            const std::string &filename_glob, const std::string &subfile_name,
                            const int observation_step);
void RefinementCondition(MeshBlockPack *pmbp);

//----------------------------------------------------------------------------------------
//! \fn ProblemGenerator::UserProblem_()
//! \brief Problem Generator for SpECTRE binary black hole initial data
//
// The following options specify the initial data to load:
//
// - problem.id_filename_glob: A glob pattern that selects the SpECTRE initial
//   data files, e.g. "path/to/data/BbhVolume*.h5".
// - problem.id_subfile_name: The name of the subfile within the H5 files that
//   contains the initial data, e.g. "VolumeData".
// - problem.id_observation_step: (Optional) The observation step to load from
//   the H5 files, in case the initial data is stored at multiple refinement
//   steps. Set to -1 to load the last step (this is the default).
void ProblemGenerator::UserProblem(ParameterInput *pin, const bool restart) {
  user_ref_func = RefinementCondition;

  if (restart)
    return;

  MeshBlockPack *pmbp = pmy_mesh_->pmb_pack;
  auto &indcs = pmy_mesh_->mb_indcs;

  // Load initial data specified by the user options
  const std::string options_block = "problem";

  std::vector<BHPosition> bh_positions;
  const int num_bhs = pin->GetInteger(options_block, "num_bhs");
  bh_positions.resize(num_bhs);
  for (int i = 0; i < num_bhs; ++i) {
    std::stringstream ss_M, ss_x, ss_y, ss_z;
    ss_M << "co_" << i << "_M";
    ss_x << "co_" << i << "_x";
    ss_y << "co_" << i << "_y";
    ss_z << "co_" << i << "_z";
    bh_positions[i].M = pin->GetReal("z4c", ss_M.str());
    bh_positions[i].x = pin->GetReal("z4c", ss_x.str());
    bh_positions[i].y = pin->GetReal("z4c", ss_y.str());
    bh_positions[i].z = pin->GetReal("z4c", ss_z.str());
  }

  LoadSpectreInitialData(
      pmbp, bh_positions,
      pin->GetOrAddString(options_block, "id_filename_glob", "EMPTY"),
      pin->GetOrAddString(options_block, "id_subfile_name", "EMPTY"),
      pin->GetOrAddInteger(options_block, "id_observation_step", -1));

  // Set lapse from conformal factor
  pmbp->pz4c->GaugePreCollapsedLapse(pmbp, pin);

  // Set Z4c variables from ADM variables
  switch (indcs.ng) {
  case 2:
    pmbp->pz4c->ADMToZ4c<2>(pmbp, pin);
    break;
  case 3:
    pmbp->pz4c->ADMToZ4c<3>(pmbp, pin);
    break;
  case 4:
    pmbp->pz4c->ADMToZ4c<4>(pmbp, pin);
    break;
  }

  // Compute ADM constrains on initial data slice
  switch (indcs.ng) {
  case 2:
    pmbp->pz4c->ADMConstraints<2>(pmbp);
    break;
  case 3:
    pmbp->pz4c->ADMConstraints<3>(pmbp);
    break;
  case 4:
    pmbp->pz4c->ADMConstraints<4>(pmbp);
    break;
  }

  std::cout << "Loading initial data complete." << std::endl;
}

//! \brief Interpolate SpECTRE initial data to AthenaK mesh
void LoadSpectreInitialData(MeshBlockPack *pmbp, const std::vector<BHPosition> &bh_positions,
                            const std::string &filename_glob, const std::string &subfile_name,
                            const int observation_step) {
  auto &u_adm = pmbp->padm->u_adm;
  HostArray5D<Real>::HostMirror host_u_adm = create_mirror(u_adm);
  z4c::Z4c::ADMhost_vars host_adm;
  host_adm.psi4.InitWithShallowSlice(host_u_adm, adm::ADM::I_ADM_PSI4);
  host_adm.g_dd.InitWithShallowSlice(
      host_u_adm, adm::ADM::I_ADM_GXX, adm::ADM::I_ADM_GZZ);
  host_adm.vK_dd.InitWithShallowSlice(
      host_u_adm, adm::ADM::I_ADM_KXX, adm::ADM::I_ADM_KZZ);
  auto &indcs = pmbp->pmesh->mb_indcs;
  auto &size = pmbp->pmb->mb_size;
  int &is = indcs.is;
  int &ie = indcs.ie;
  int &js = indcs.js;
  int &je = indcs.je;
  int &ks = indcs.ks;
  int &ke = indcs.ke;
  // For GLOOPS
  int isg = is - indcs.ng;
  int ieg = ie + indcs.ng;
  int jsg = js - indcs.ng;
  int jeg = je + indcs.ng;
  int ksg = ks - indcs.ng;
  int keg = ke + indcs.ng;

  int nx1 = indcs.nx1;
  int nx2 = indcs.nx2;
  int nx3 = indcs.nx3;
  int ncells1 = nx1 + 2 * (indcs.ng);
  int ncells2 = nx2 + 2 * (indcs.ng);
  int ncells3 = nx3 + 2 * (indcs.ng);
  int n[3] = {ncells1, ncells2, ncells3};
  int sz = n[0] * n[1] * n[2];

  // Allocate memory for the coordinates
  std::array<std::vector<double>, 3> x{};
  x[0].resize(sz);
  x[1].resize(sz);
  x[2].resize(sz);

  int nmb = pmbp->nmb_thispack;
  Kokkos::Timer timer{};
  for (int m = 0; m < nmb; ++m) {
    // Get the coordinates for this meshblock
    Real &x1min = size.h_view(m).x1min;
    Real &x1max = size.h_view(m).x1max;
    Real &x2min = size.h_view(m).x2min;
    Real &x2max = size.h_view(m).x2max;
    Real &x3min = size.h_view(m).x3min;
    Real &x3max = size.h_view(m).x3max;
    for (int ix_I = isg; ix_I < ieg + 1; ix_I++) {
      for (int ix_J = jsg; ix_J < jeg + 1; ix_J++) {
        for (int ix_K = ksg; ix_K < keg + 1; ix_K++) {
          int flat_ix = ix_I + n[0] * (ix_J + n[1] * ix_K);
          x[0][flat_ix] = CellCenterX(ix_I - is, nx1, x1min, x1max);
          x[1][flat_ix] = CellCenterX(ix_J - js, nx2, x2min, x2max);
          x[2][flat_ix] = CellCenterX(ix_K - ks, nx3, x3min, x3max);
        }
      }
    }

    // Interpolate data to the coordinates
    timer.reset();
    std::cout << "Interpolating initial data for meshblock " << m << "/"
              << nmb - 1 << " with " << sz << " points..." << std::endl;
    const auto data = spectre::Exporter::interpolate_to_points<3>(
        filename_glob, subfile_name, spectre::Exporter::ObservationStep{observation_step},
        {"Field", "TracelessConformalExtrinsicCurvature_xx", "TracelessConformalExtrinsicCurvature_yx",
         "TracelessConformalExtrinsicCurvature_zx", "TracelessConformalExtrinsicCurvature_yy",
         "TracelessConformalExtrinsicCurvature_zy", "TracelessConformalExtrinsicCurvature_zz"},
        /* target_points */ x,
        /* extrapolate_into_excisions */ true);
    std::cout << "  done in " << timer.seconds() << " seconds." << std::endl;

    const auto &u = data[0];
    const auto &A_xx = data[1];
    const auto &A_xy = data[2];
    const auto &A_xz = data[3];
    const auto &A_yy = data[4];
    const auto &A_yz = data[5];
    const auto &A_zz = data[6];

    // Move the interpolated data into the meshblock
    for (int k = ksg; k <= keg; k++)
      for (int j = jsg; j <= jeg; j++)
        for (int i = isg; i <= ieg; i++) {
          int flat_ix = i + n[0] * (j + n[1] * k);
          Real xp = x[0][flat_ix];
          Real yp = x[1][flat_ix];
          Real zp = x[2][flat_ix];

          Real psi = 1.0 + u[flat_ix];
          for (const auto &bh_pos : bh_positions) {
            Real dx = xp - bh_pos.x;
            Real dy = yp - bh_pos.y;
            Real dz = zp - bh_pos.z;
            Real r = std::sqrt(dx * dx + dy * dy + dz * dz);
            r = std::max(r, 1e-5); // avoid singularity at puncture
            psi += bh_pos.M / (2.0 * r);
          }

          Real psi4 = std::pow(psi, 4);
          host_adm.psi4(m, k, j, i) = psi4;
          host_adm.g_dd(m, 0, 0, k, j, i) = psi4;
          host_adm.g_dd(m, 1, 1, k, j, i) = psi4;
          host_adm.g_dd(m, 2, 2, k, j, i) = psi4;
          host_adm.g_dd(m, 0, 1, k, j, i) = 0.0;
          host_adm.g_dd(m, 0, 2, k, j, i) = 0.0;
          host_adm.g_dd(m, 1, 2, k, j, i) = 0.0;

          Real psim2 = std::pow(psi, -2);
          host_adm.vK_dd(m, 0, 0, k, j, i) = psim2 * A_xx[flat_ix];
          host_adm.vK_dd(m, 1, 1, k, j, i) = psim2 * A_yy[flat_ix];
          host_adm.vK_dd(m, 2, 2, k, j, i) = psim2 * A_zz[flat_ix];
          host_adm.vK_dd(m, 0, 1, k, j, i) = psim2 * A_xy[flat_ix];
          host_adm.vK_dd(m, 0, 2, k, j, i) = psim2 * A_xz[flat_ix];
          host_adm.vK_dd(m, 1, 2, k, j, i) = psim2 * A_yz[flat_ix];
        }
  }
  Kokkos::deep_copy(u_adm, host_u_adm);
}

void RefinementCondition(MeshBlockPack *pmbp) {
  pmbp->pz4c->pamr->Refine(pmbp);
}
