#ifndef PARTICLES_DEPOSIT_SHAPE_HPP_
#define PARTICLES_DEPOSIT_SHAPE_HPP_
//========================================================================================
// AthenaXXX astrophysical plasma code
// Copyright(C) 2020 James M. Stone <jmstone@ias.edu> and the Athena code team
// Licensed under the 3-clause BSD License (the "LICENSE")
//========================================================================================
//! \file deposit_shape.hpp
//! \brief tensor-product particle->mesh shape functions for the NRPIC Tmunu deposition.
//!
//! The deposition in particles_tmunu.cpp is a SCATTER: each particle adds
//! amp * Phi(...) / (sqrt(gamma) dV) into the cells of its stencil. The only property
//! required for the exact conservation identity
//!
//!     sum_cells q sqrt(gamma) dV == sum_p amp_q                                    (I)
//!
//! is that the 1D shape function have unit partition,  sum_n Phi(q-n) == 1  for every
//! q, and that each stencil cell be deposited exactly once. Everything below satisfies
//! the first identically (verified symbolically in scripts/kernel_reference.py); the
//! image architecture in particles_tmunu.cpp supplies the second.
//!
//! KERNELS. The three shape functions of Diener, Rosswog & Torsello, Eur. Phys. J. A 58,
//! 74 (2022), Sec. 2.1.3, Eqs. (23)-(25) -- originally Cottet, Etancelin, Perignon &
//! Picard, ESAIM:M2AN 48, 1029 (2014) -- plus the pre-existing CIC as the W = 2 member of
//! the same family. In Cottet's notation Lambda_{p,r} reproduces polynomials up to degree
//! p (order p+1) and is C^r:
//!
//!   cic       W=2  order 2  C^0   linear B-spline M2; the historical AthenaK deposition
//!   m4        W=4  order 2  C^2   cubic B-spline; POSITIVE DEFINITE; the MOOD parachute
//!   lambda22  W=4  order 3  C^2   Eq. (24); one negative lobe; second moment M2 == 0
//!   lambda44  W=6  order 5  C^4   Eq. (23); negative lobes; M2 == M4 == 0
//!
//! Monaghan's theorem (their ref. [73]) says a positive-definite shape function can be at
//! most order two, so orders above two necessarily carry negative lobes -- the reason the
//! MOOD fallback in particles_mood.cpp exists.
//!
//! EVALUATION FORM. Each piece is stored re-expanded about its own left knot,
//! P_k(t) = Phi(k+t) for t in [0,1], and evaluated by Horner in t. A stencil offset
//! always
//! gives |q| = delta + m (low side: piece m, t = delta) or |q| = m - delta (high side:
//! piece m-1, t = 1-delta), so no other evaluation point is ever needed. This matters:
//! evaluating the PUBLISHED form of Lambda_{4,4} on 2 <= |q| < 3 -- a degree-9 polynomial
//! with coefficients up to 89235/4 returning values of order 1e-3 -- loses
//! catastrophically
//! to cancellation, giving max|sum_s w_s - 1| = 4.6e-10 against 1.1e-14 for the shifted
//! form (scripts/emit_kernel_coeffs.py). At N = 4.2e6 particles the published form alone
//! would violate the identity tolerance in (I).
//!
//! Coefficients below are generated by scripts/emit_kernel_coeffs.py.

#include <cmath>

#include "athena.hpp"
#include "coordinates/cell_locations.hpp"

namespace particles {

//----------------------------------------------------------------------------------------
//! \brief selectable deposition shape function. `cic` reproduces the historical kernel
//! bitwise (its weights are the literal {1-delta, delta} pair, not P_0 evaluations).

enum class DepositShape {cic, m4, lambda22, lambda44};

// widest stencil supported, and the widest half-support in cells (= kMaxShapeWidth/2).
// Every fixed-size stencil array in the deposit path is sized by these.
constexpr int kMaxShapeWidth = 6;
constexpr int kMaxShapeHalf  = 3;

//----------------------------------------------------------------------------------------
//! \fn int ShapeWidth()
//! \brief number of cells the stencil spans per dimension.

KOKKOS_INLINE_FUNCTION
constexpr int ShapeWidth(DepositShape s) {
  return (s == DepositShape::cic) ? 2 : ((s == DepositShape::lambda44) ? 6 : 4);
}

//----------------------------------------------------------------------------------------
//! \fn int ShapeOffset()
//! \brief offset s0 of the leftmost stencil cell relative to the LeftCenterIndex anchor,
//! s0 = -(W/2 - 1). Stencil cells are idx + s0 + s for s = 0 .. W-1.

KOKKOS_INLINE_FUNCTION
constexpr int ShapeOffset(DepositShape s) {
  return -(ShapeWidth(s)/2 - 1);
}

//----------------------------------------------------------------------------------------
//! \fn int ShapeHalf()
//! \brief support half-width in cells; also the maximum overhang of the stencil beyond a
//! block face, so nghost >= ShapeHalf() and nx >= ShapeWidth() are the mesh requirements.

KOKKOS_INLINE_FUNCTION
constexpr int ShapeHalf(DepositShape s) {
  return ShapeWidth(s)/2;
}

//----------------------------------------------------------------------------------------
//! \fn const Real* ShapeCoeffs()
//! \brief ascending-power coefficients of P_k(t) = Phi(k + t), t in [0,1], padded with
//! zeros to kMaxShapeDegree+1. Exposing the table (rather than hard-coding Horner
//! expressions) lets the unit test differentiate the pieces exactly and verify the
//! smoothness class at every knot, instead of estimating it by finite differences.
//! Generated by scripts/emit_kernel_coeffs.py; k must be < ShapeHalf(shape).

constexpr int kMaxShapeDegree = 9;

KOKKOS_INLINE_FUNCTION
void ShapeCoeffs(DepositShape shape, int k, Real c[kMaxShapeDegree+1], int &deg) {
  for (int i=0; i<=kMaxShapeDegree; ++i) {c[i] = 0.0;}
  switch (shape) {
    case DepositShape::cic:                                    // P_0 = 1 - t
      deg = 1;
      c[0] = 1.0; c[1] = -1.0;
      return;
    case DepositShape::m4:
      deg = 3;
      if (k == 0) {                                            // 2/3 - t^2 + t^3/2
        c[0] = 2.0/3.0; c[2] = -1.0; c[3] = 0.5;
      } else {                                            // 1/6 - t/2 + t^2/2 - t^3/6
        c[0] = 1.0/6.0; c[1] = -0.5; c[2] = 0.5; c[3] = -1.0/6.0;
      }
      return;
    case DepositShape::lambda22:
      deg = 5;
      if (k == 0) {              // 1 - t^2 - 9/2 t^3 + 15/2 t^4 - 3 t^5
        c[0] = 1.0; c[2] = -1.0; c[3] = -4.5; c[4] = 7.5; c[5] = -3.0;
      } else {                   // -t/2 + t^2/2 + 3/2 t^3 - 5/2 t^4 + t^5
        c[1] = -0.5; c[2] = 0.5; c[3] = 1.5; c[4] = -2.5; c[5] = 1.0;
      }
      return;
    case DepositShape::lambda44:
      deg = 9;
      if (k == 0) {
        // 1 - 5/4 t^2 + 1/4 t^4 - 100/3 t^5 + 455/4 t^6 - 295/2 t^7 + 345/4 t^8
        //   - 115/6 t^9
        c[0] = 1.0;          c[2] = -1.25;        c[4] = 0.25;
        c[5] = -100.0/3.0;   c[6] = 455.0/4.0;    c[7] = -295.0/2.0;
        c[8] = 345.0/4.0;    c[9] = -115.0/6.0;
      } else if (k == 1) {
        // -2/3 t + 2/3 t^2 + 1/6 t^3 - 1/6 t^4 + 50/3 t^5 - 455/8 t^6 + 295/4 t^7
        //   - 345/8 t^8 + 115/12 t^9
        c[1] = -2.0/3.0;     c[2] = 2.0/3.0;      c[3] = 1.0/6.0;
        c[4] = -1.0/6.0;     c[5] = 50.0/3.0;     c[6] = -455.0/8.0;
        c[7] = 295.0/4.0;    c[8] = -345.0/8.0;   c[9] = 115.0/12.0;
      } else {
        // 1/12 t - 1/24 t^2 - 1/12 t^3 + 1/24 t^4 - 10/3 t^5 + 91/8 t^6 - 59/4 t^7
        //   + 69/8 t^8 - 23/12 t^9
        c[1] = 1.0/12.0;     c[2] = -1.0/24.0;    c[3] = -1.0/12.0;
        c[4] = 1.0/24.0;     c[5] = -10.0/3.0;    c[6] = 91.0/8.0;
        c[7] = -59.0/4.0;    c[8] = 69.0/8.0;     c[9] = -23.0/12.0;
      }
      return;
  }
  deg = 0;
}

//----------------------------------------------------------------------------------------
//! \fn Real ShapePiece()
//! \brief P_k(t) = Phi(k + t) for t in [0,1], Horner in t. `k` must be < ShapeHalf().

KOKKOS_INLINE_FUNCTION
Real ShapePiece(DepositShape shape, int k, Real t) {
  Real c[kMaxShapeDegree+1];
  int deg = 0;
  ShapeCoeffs(shape, k, c, deg);
  Real v = c[deg];
  for (int i=deg-1; i>=0; --i) {v = v*t + c[i];}
  return v;
}

//----------------------------------------------------------------------------------------
//! \fn void ShapeWeights()
//! \brief fill w[0 .. W-1] for stencil cells idx + s0 + s, given delta in [0,1].
//!
//! For stencil offset o = s + s0 the kernel argument is |q| = delta - o, so
//!   o <= 0 : |q| = delta + (-o)  -> piece k = -o,  t = delta
//!   o >= 1 : |q| = o - delta     -> piece k = o-1, t = 1 - delta
//! and no piece boundary is ever straddled.
//!
//! `renorm` divides by the weight sum. Partition of unity is exact in exact arithmetic,
//! so this only removes the ~1e-14 floating-point defect of the Horner evaluation; it
//! must
//! be applied to the FULL W weights, before any boundary clipping (the clipped remainder
//! is the accounted f_p). It is a structural no-op for cic, whose weights are the exact
//! pair {1-delta, delta} so that the historical kernel is reproduced bit for bit.

KOKKOS_INLINE_FUNCTION
void ShapeWeights(DepositShape shape, Real delta, bool renorm, Real w[kMaxShapeWidth]) {
  if (shape == DepositShape::cic) {
    w[0] = 1.0 - delta;
    w[1] = delta;
    return;
  }
  const int width = ShapeWidth(shape);
  const int s0 = ShapeOffset(shape);
  Real sum = 0.0;
  for (int s=0; s<width; ++s) {
    int o = s + s0;
    Real v = (o <= 0) ? ShapePiece(shape, -o, delta)
                      : ShapePiece(shape, o - 1, 1.0 - delta);
    w[s] = v;
    sum += v;
  }
  if (renorm && sum != 0.0) {
    Real inv = 1.0/sum;
    for (int s=0; s<width; ++s) {w[s] *= inv;}
  }
}

//----------------------------------------------------------------------------------------
//! \fn int LeftCenterIndexWide()
//! \brief LeftCenterIndex WITHOUT the [-1, n-1] clamp.
//!
//! cell_locations.hpp::LeftCenterIndex hard-clamps its result to [-1, n-1]. For CIC that
//! is harmless: DepositCloudNative's 2-point keep test (0 <= c < n) rejects the clamped
//! values. For a half-width-3 stencil it is NOT: a particle up to 3 cells outside the
//! target block would have its clamped anchor produce spurious deposits into cells 0 or
//! n-1. This variant keeps the same comparison-corrected predicate -- the largest i with
//! CellCenterX(i) <= x -- but lets i run outside [0, n-1]. CellCenterX extrapolates
//! linearly for any integer, so this is well defined; for x inside [xmin, xmax) it
//! returns
//! bitwise the same index as LeftCenterIndex.

KOKKOS_INLINE_FUNCTION
int LeftCenterIndexWide(Real x, int n, Real xmin, Real xmax) {
  Real dx = (xmax - xmin)/static_cast<Real>(n);
  int idx = static_cast<int>(floor((x - xmin)/dx - 0.5));
  // the float guess is off by at most one cell; one comparison step each way corrects it
  if (CellCenterX(idx+1, n, xmin, xmax) <= x) {
    ++idx;
  } else if (CellCenterX(idx, n, xmin, xmax) > x) {
    --idx;
  }
  return idx;
}

} // namespace particles

#endif // PARTICLES_DEPOSIT_SHAPE_HPP_
