//========================================================================================
// AthenaXXX astrophysical plasma code
// Copyright(C) 2020 James M. Stone <jmstone@ias.edu> and the Athena code team
// Licensed under the 3-clause BSD License (the "LICENSE")
//========================================================================================
//! \file particles_mood.cpp
//! \brief MOOD ("Multidimensional Optimal Order Detection") fallback for the higher-order
//! particle->mesh Tmunu deposition.
//!
//! Follows Diener, Rosswog & Torsello, Eur. Phys. J. A 58, 74 (2022), Sec. 2.1.3: attempt
//! the highest-order shape function, detect a posteriori whether the mapped grid values
//! are supportable by the contributing particles, and fall back down the hierarchy
//! Lambda_{4,4} -> Lambda_{2,2} -> M_4 where they are not, with the positive-definite
//! M_4 as the untested "parachute". Two deliberate and necessary departures:
//!
//! (1) THE DECISION UNIT IS THE PARTICLE, NOT THE GRID POINT. Their mapping is a
//!     normalised gather, so each grid point is independent and may pick its own kernel
//! --
//!     which is exactly why their mapping is not conservative. Ours is a scatter, where
//!     the unit whose weights must sum to one is the particle. Overriding the kernel at
//!     one cell of a particle's stencil would break sum_s w_s = 1 for that particle and
//!     destroy the exact identity  sum_cells q sqrt(gamma) dV == sum_p amp_q. So every
//!     particle deposits with exactly one kernel, and since every kernel in the hierarchy
//!     has unit partition, CONSERVATION IS EXACT FOR ANY ASSIGNMENT OF KERNELS TO
//!     PARTICLES. Corollary: a mistake in the detector below is a quality issue, never a
//!     correctness issue.
//!
//! (2) THE ADMISSIBILITY TEST IS A CONE MEMBERSHIP, NOT A VALUE BRACKET. Their test is
//!     T^g_{mu nu} in [min_p, max_p] over the contributing particles -- meaningful when
//!     the grid value interpolates particle-carried field values. Our grid value is a
//!     DENSITY assembled from extensive amplitudes, so that comparison is a category
//!     error. The sharp analogue: particle p contributes
//!     A_p = (m W, m u_a, (m/W) u_a u_b), and for ANY non-negative weights w_p,
//!
//!         sum_p w_p [ t sqrt(W_p) + u_a v^a / sqrt(W_p) ]^2 >= 0   for all (t, v^a)
//!     <=> t^2 E + 2 t v^a S_a + v^a v^b S_ab >= 0
//!     <=> the 4x4 symmetric matrix  M = [[E, S_b], [S_a, S_ab]]  is positive semi-def.
//!
//!     So M >= 0 is a PROVABLE consequence of any positive-kernel deposition, and a
//!     violation proves the value lies outside the cone generated by the contributing
//!     particles -- which is what "outside the range of the contributing particles" means
//!     once the quantity is a density. The form acts on (t, v^a) with all indices already
//!     lowered, so it needs no metric. Implemented as the order-1 and order-2 principal
//!     minors, all of which are necessary conditions.
//!
//! GETTING THE FLAG BACK TO THE PARTICLES. A particle's stencil can reach cells owned by
//! another MeshBlock on another rank, but the demotion must be identical on every record
//! of that particle, so it has to be decided on the source rank. The flag is therefore
//! written on physical cells and then GHOST-FILLED with the standard cell-centred
//! machinery (the same synchronous sequence tmunu_filter.cpp uses), after which the
//! source
//! rank sees the particle's whole stencil locally: nghost = 4 >= ShapeHalf = 3. At an SMR
//! seam the 2nd-order restriction/prolongation blurs the flag, which can only OVER-flag
//! --
//! harmless by the corollary above.

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

#include "athena.hpp"
#include "globals.hpp"
#include "mesh/mesh.hpp"
#include "coordinates/adm.hpp"
#include "coordinates/cell_locations.hpp"
#include "z4c/z4c.hpp"
#include "z4c/tmunu.hpp"
#include "bvals/bvals.hpp"
#include "particles.hpp"
#include "deposit_shape.hpp"

#if MPI_PARALLEL_ENABLED
#include <mpi.h>
#endif

namespace particles {

// Threshold for "this cell is flagged". NOT 0.5: MoodFillGhosts restricts the 0/1 flag
// into a coarse block's seam ghosts with the plain 8-point average
// (MeshRefinement::RestrictCC), so ONE flagged fine cell arrives as 1/8 = 0.125 and fewer
// than five of eight always under-flags. Under-flagging is the one failure mode that is
// NOT safe: it leaves a cell inadmissible for ever, the cascade runs its full sweep
// budget
// every cycle, and nbad_final reads as "cascade exhausted" when the real cause is a lost
// flag. Any non-zero restricted value must count, so the threshold sits below the
// smallest
// non-zero restriction weight (1/8) and above float round-off. Prolongation
// (coarse->fine)
// is minmod-limited and cannot undershoot a 0/1 field, so that direction over-flags,
// which
// IS safe.
constexpr Real kMoodFlagged = 1.0e-3;

//----------------------------------------------------------------------------------------
//! \fn void Particles::MoodAllocate()
//! \brief read the deposition/MOOD parameters, validate them against the mesh, and
//! allocate. Called from the constructor's feedback branch only.

void Particles::MoodAllocate(ParameterInput *pin) {
  auto &indcs = pmy_pack->pmesh->mb_indcs;

  std::string shp = pin->GetOrAddString("particles", "deposit_shape", "cic");
  if (shp.compare("cic") == 0) {
    deposit_shape = DepositShape::cic;
  } else if (shp.compare("m4") == 0) {
    deposit_shape = DepositShape::m4;
  } else if (shp.compare("lambda22") == 0) {
    deposit_shape = DepositShape::lambda22;
  } else if (shp.compare("lambda44") == 0) {
    deposit_shape = DepositShape::lambda44;
  } else {
    std::cout << "### FATAL ERROR in " << __FILE__ << " at line " << __LINE__ << std::endl
              << "<particles> deposit_shape = '" << shp << "' not recognized; use "
              << "'cic', 'm4', 'lambda22' or 'lambda44'." << std::endl;
    std::exit(EXIT_FAILURE);
  }
  deposit_renorm = pin->GetOrAddBoolean("particles", "deposit_renorm", true);
  deposit_generic_cic =
      pin->GetOrAddBoolean("particles", "deposit_generic_cic", false);

  // MOOD hierarchy: deposit_shape names the top, the cascade below it is fixed.
  bool want_mood = pin->GetOrAddBoolean("particles", "mood", false);
  if (deposit_shape == DepositShape::lambda44) {
    mood_nlevels = 3;
    mood_hier[0] = DepositShape::lambda44;
    mood_hier[1] = DepositShape::lambda22;
    mood_hier[2] = DepositShape::m4;
  } else if (deposit_shape == DepositShape::lambda22) {
    mood_nlevels = 2;
    mood_hier[0] = DepositShape::lambda22;
    mood_hier[1] = DepositShape::m4;
    mood_hier[2] = DepositShape::m4;
  } else {
    mood_nlevels = 1;
    mood_hier[0] = deposit_shape;
    mood_hier[1] = deposit_shape;
    mood_hier[2] = deposit_shape;
  }
  if (want_mood && mood_nlevels == 1 && global_variable::my_rank == 0) {
    std::cout << "### WARNING in " << __FILE__ << " at line " << __LINE__ << std::endl
              << "<particles> mood = true with deposit_shape = '" << shp << "' has no"
              << " lower-order kernel to fall back to (that shape is already positive"
              << " definite or is the historical CIC); MOOD is inert." << std::endl;
  }
  mood_on = want_mood && (mood_nlevels > 1);
  // MONITOR-ONLY mode: run the admissibility detector at the diagnostic cadence and
  // report
  // it, but never demote. This is how a pure higher-order run (mood = false) still
  // reports
  // its negative-E / inadmissible-cell incidence, which for a mixed-sign kernel at low
  // particles-per-cell is the number that matters. Costs one full-mesh pass and two
  // reductions per reported cycle, nothing on the other cycles.
  mood_monitor = pin->GetOrAddBoolean("particles", "mood_monitor", false) && !mood_on;
  mood_max_sweeps = pin->GetOrAddInteger("particles", "mood_max_sweeps", 4);
  std::string det = pin->GetOrAddString("particles", "mood_detector", "psd2");
  if (det.compare("psd2") == 0) {
    mood_detector = 2;
  } else if (det.compare("e_positive") == 0) {
    mood_detector = 1;
  } else if (det.compare("off") == 0) {
    mood_detector = 0;
  } else {
    std::cout << "### FATAL ERROR in " << __FILE__ << " at line " << __LINE__ << std::endl
              << "<particles> mood_detector = '" << det << "' not recognized; use "
              << "'psd2', 'e_positive' or 'off'." << std::endl;
    std::exit(EXIT_FAILURE);
  }
  mood_tol = pin->GetOrAddReal("particles", "mood_tol", 1.0e-12);
  // Raises the bar from "negative at all" to "negative by this fraction of the peak
  // energy
  // density". Default 0 = the strict, tolerance-free criterion of the paper. See
  // notes/ppc_criterion.md: with fewer than ~180 particles per kernel cell the per-cell
  // shot noise exceeds the kernel's Gibbs undershoot, the strict test fires on the bulk
  // of
  // the interior, and only a raised bar keeps MOOD a guard rather than a bulk demoter.
  mood_neg_frac = pin->GetOrAddReal("particles", "mood_neg_frac", 0.0);
  // NOT max(1, <time>/ndiag): ndiag <= 0 is the "never print" convention and must not
  // become "every cycle". <= 0 here means never.
  mood_diag_cadence = pin->GetOrAddInteger("particles", "mood_diag_cadence",
                                           pin->GetOrAddInteger("time", "ndiag", 1));
  mood_nbin = std::max(0, pin->GetOrAddInteger("particles", "mood_hist_nbin", 64));
  mood_rmax = pin->GetOrAddReal("particles", "mood_hist_rmax", 0.0);
  mood_center[0] = pin->GetOrAddReal("particles", "mood_center_x1", 0.0);
  mood_center[1] = pin->GetOrAddReal("particles", "mood_center_x2", 0.0);
  mood_center[2] = pin->GetOrAddReal("particles", "mood_center_x3", 0.0);
  mood_log_fname = pin->GetString("job", "basename") + ".mood.csv";

  // ---- mesh requirements of a wide stencil
  // ---------------------------------------------
  // The stencil overhangs a block face by at most ShapeHalf cells, and beff[3] in
  // prtcl_search.hpp carries ONE signed direction per axis, so a stencil must never
  // overhang both faces of the same axis. Both conditions reduce to nx >= W.
  int wmax = ShapeWidth(deposit_shape);
  for (int l=0; l<mood_nlevels; ++l) {
    wmax = std::max(wmax, ShapeWidth(mood_hier[l]));
  }
  int nxmin = indcs.nx1;
  if (pmy_pack->pmesh->multi_d) {nxmin = std::min(nxmin, indcs.nx2);}
  if (pmy_pack->pmesh->three_d) {nxmin = std::min(nxmin, indcs.nx3);}
  if (nxmin < wmax) {
    std::cout << "### FATAL ERROR in " << __FILE__ << " at line " << __LINE__ << std::endl
              << "<particles> deposit_shape = '" << shp << "' has a " << wmax
              << "-cell stencil, but the smallest MeshBlock dimension is " << nxmin
              << ". A stencil that overhangs BOTH faces of one axis cannot be routed"
              << std::endl
              << "(the image band carries one signed direction per axis). Require"
              << " nx1,nx2,nx3 >= " << wmax << "." << std::endl;
    std::exit(EXIT_FAILURE);
  }
  if (mood_on && indcs.ng < wmax/2) {
    std::cout << "### FATAL ERROR in " << __FILE__ << " at line " << __LINE__ << std::endl
              << "<particles> mood = true needs nghost >= " << (wmax/2)
              << " so a particle's whole stencil is visible in its own block's ghost"
              << " zone after the flag exchange; nghost = " << indcs.ng << "."
              << std::endl;
    std::exit(EXIT_FAILURE);
  }

  Kokkos::realloc(deposit_order_p, 1);
  Kokkos::realloc(tmunu_recv_slot, 1);
  Kokkos::realloc(tmunu_lor, 1);
  Kokkos::realloc(tmunu_finestencil, 1);

  if (mood_on || mood_monitor) {
    int nmb = std::max((pmy_pack->nmb_thispack), (pmy_pack->pmesh->nmb_maxperrank));
    int ncells1 = indcs.nx1 + 2*(indcs.ng);
    int ncells2 = (indcs.nx2 > 1) ? (indcs.nx2 + 2*(indcs.ng)) : 1;
    int ncells3 = (indcs.nx3 > 1) ? (indcs.nx3 + 2*(indcs.ng)) : 1;
    Kokkos::realloc(u_mood, nmb, 1, ncells3, ncells2, ncells1);
    if (pmy_pack->pmesh->multilevel) {
      int nc1 = indcs.cnx1 + 2*(indcs.ng);
      int nc2 = (indcs.cnx2 > 1) ? (indcs.cnx2 + 2*(indcs.ng)) : 1;
      int nc3 = (indcs.cnx3 > 1) ? (indcs.cnx3 + 2*(indcs.ng)) : 1;
      Kokkos::realloc(coarse_u_mood, nmb, 1, nc3, nc2, nc1);
    }
    Kokkos::realloc(mood_ncell, 5);   // per-criterion cell census
    Kokkos::realloc(mood_level_ct, 3);
    Kokkos::realloc(mood_radial, std::max(1, mood_nbin*3));
    if (mood_on) {
      pbval_mood = new MeshBoundaryValuesCC(pmy_pack, pin, false);
      pbval_mood->InitializeBuffers(1);
    }
  }

  if (global_variable::my_rank == 0) {
    std::cout << "[deposit] shape=" << shp
              << " width=" << ShapeWidth(deposit_shape)
              << " renorm=" << (deposit_renorm ? "true" : "false")
              << " generic_cic=" << (deposit_generic_cic ? "true" : "false")
              << " mood=" << (mood_on ? "true" : "false")
              << " mood_monitor=" << (mood_monitor ? "true" : "false");
    if (mood_on) {
      std::cout << " levels=" << mood_nlevels
                << " max_sweeps=" << mood_max_sweeps
                << " detector=" << det
                << " tol=" << mood_tol;
      std::size_t bytes = (u_mood.size() + coarse_u_mood.size())*sizeof(Real);
      std::size_t buf = 0;
      if (pbval_mood != nullptr) {
        for (int n=0; n<56; ++n) {
          buf += (pbval_mood->sendbuf[n].vars.size()
                + pbval_mood->recvbuf[n].vars.size())*sizeof(Real);
        }
      }
      std::cout << " extra_dev_mem=" << (bytes + buf)/1048576.0 << " MiB";
    }
    std::cout << std::endl;
  }
}

//----------------------------------------------------------------------------------------
//! \fn int Particles::MoodDetect()
//! \brief write the inadmissibility flag on every PHYSICAL cell (every mesh cell is a
//! physical cell of exactly one block, so this is complete coverage without ghosts) and
//! return the GLOBAL number of flagged cells.
//!
//! Tolerances are scaled by the global max E so that a round-off negative
//! (|E| ~ 1e-16 E_local) is six orders of magnitude away from a genuine negative-lobe
//! undershoot (|E| ~ 4e-2 E_interior at a sharp surface).

int Particles::MoodDetect() {
  auto &indcs = pmy_pack->pmesh->mb_indcs;
  int is = indcs.is, ie = indcs.ie;
  int js = indcs.js, je = indcs.je;
  int ks = indcs.ks, ke = indcs.ke;
  int nmb = pmy_pack->nmb_thispack;
  auto &tmunu = pmy_pack->ptmunu->tmunu;
  auto &flag = u_mood;
  int detector = mood_detector;
  Real tolr = mood_tol;

  // zero the whole array (ghosts included: the fill below overwrites only what it owns)
  Kokkos::deep_copy(flag, 0.0);
  if (detector == 0) {return 0;}

  // global scale = max E over physical cells
  Real emax = 0.0;
  Kokkos::parallel_reduce("mood_emax",
    Kokkos::MDRangePolicy<Kokkos::Rank<4>>(DevExeSpace(), {0,ks,js,is},
                                           {nmb,ke+1,je+1,ie+1}),
    KOKKOS_LAMBDA(const int m, const int k, const int j, const int i, Real &mx) {
      Real e = tmunu.E(m,k,j,i);
      if (e > mx) {mx = e;}
    }, Kokkos::Max<Real>(emax));
#if MPI_PARALLEL_ENABLED
  MPI_Allreduce(MPI_IN_PLACE, &emax, 1, MPI_ATHENA_REAL, MPI_MAX,
                pbval_part->mpi_comm_part);
#endif
  if (!(emax > 0.0)) {emax = std::numeric_limits<Real>::min();}
  Real tol_e = tolr*emax;

  // Per-criterion census, so the report can say WHICH inequality fires rather than only
  // how many cells did: {E<0, S_aa<0, E*S_aa-S_a^2<0, S_aa*S_bb-S_ab^2<0, non-finite}.
  Kokkos::deep_copy(mood_ncell, 0);
  auto &ncrit = mood_ncell;
  Real negfrac = mood_neg_frac;

  int nbad = 0;
  Kokkos::parallel_reduce("mood_detect",
    Kokkos::MDRangePolicy<Kokkos::Rank<4>>(DevExeSpace(), {0,ks,js,is},
                                           {nmb,ke+1,je+1,ie+1}),
    KOKKOS_LAMBDA(const int m, const int k, const int j, const int i, int &cnt) {
      Real E = tmunu.E(m,k,j,i);
      Real Sd[3] = {tmunu.S_d(m,0,k,j,i), tmunu.S_d(m,1,k,j,i), tmunu.S_d(m,2,k,j,i)};
      bool bad = false;
      if (!Kokkos::isfinite(E) || !Kokkos::isfinite(Sd[0]) ||
          !Kokkos::isfinite(Sd[1]) || !Kokkos::isfinite(Sd[2])) {
        bad = true;
        Kokkos::atomic_add(&ncrit(4), 1);
      }
      // order-1 minor on the E row. `negfrac` (mood_neg_frac) raises the bar from
      // "negative at all" to "negative by a stated fraction of the peak energy density",
      // which is what turns MOOD from a bulk demoter into a guard when the per-cell shot
      // noise is larger than the kernel's Gibbs undershoot (see notes/ppc_criterion.md).
      Real e_thresh = -fmax(tol_e, negfrac*emax);
      if (!bad && E < e_thresh) {
        bad = true;
        Kokkos::atomic_add(&ncrit(0), 1);
      }
      if (!bad && detector >= 2) {
        for (int a=0; a<3 && !bad; ++a) {
          Real Saa = tmunu.S_dd(m,a,a,k,j,i);
          if (!Kokkos::isfinite(Saa)) {
            bad = true; Kokkos::atomic_add(&ncrit(4), 1); break;
          }
          if (Saa < e_thresh) {
            bad = true; Kokkos::atomic_add(&ncrit(1), 1); break;
          }
          // 2x2 principal minor with the E row. The bound is formed as a product of
          // O(E) quantities so it neither overflows nor underflows the way tol*emax*emax
          // would for |E| outside ~1e-150..1e150, and it degrades to a RELATIVE test when
          // the entries themselves are large.
          Real m2 = E*Saa - Sd[a]*Sd[a];
          Real sc = fmax(fabs(E*Saa), emax*emax);
          if (m2 < -fmax(tolr*sc, negfrac*sc)) {
            bad = true; Kokkos::atomic_add(&ncrit(2), 1); break;
          }
        }
        for (int a=0; a<3 && !bad; ++a) {
          for (int b=a+1; b<3 && !bad; ++b) {
            Real Saa = tmunu.S_dd(m,a,a,k,j,i);
            Real Sbb = tmunu.S_dd(m,b,b,k,j,i);
            Real Sab = tmunu.S_dd(m,a,b,k,j,i);
            if (!Kokkos::isfinite(Sab)) {
              bad = true; Kokkos::atomic_add(&ncrit(4), 1); break;
            }
            Real m2 = Saa*Sbb - Sab*Sab;
            Real sc = fmax(fabs(Saa*Sbb), emax*emax);
            if (m2 < -fmax(tolr*sc, negfrac*sc)) {
              bad = true; Kokkos::atomic_add(&ncrit(3), 1);
            }
          }
        }
      }
      if (bad) {
        flag(m,0,k,j,i) = 1.0;
        ++cnt;
      }
    }, Kokkos::Sum<int>(nbad));
#if MPI_PARALLEL_ENABLED
  MPI_Allreduce(MPI_IN_PLACE, &nbad, 1, MPI_INT, MPI_SUM, pbval_part->mpi_comm_part);
#endif
  return nbad;
}

//----------------------------------------------------------------------------------------
//! \fn void Particles::MoodFillGhosts()
//! \brief synchronous cell-centred ghost fill of the one-component flag, using the proven
//! driver-init sequence (identical to Tmunu::FillTmunuGhosts). Physical outer boundaries
//! keep zero ghosts, which is correct: there is no matter there.

void Particles::MoodFillGhosts() {
  auto pm = pmy_pack->pmesh;
  if (pm->multilevel) {
    pm->pmr->RestrictCC(u_mood, coarse_u_mood);
  }
  (void) pbval_mood->InitRecv(1);
  (void) pbval_mood->PackAndSendCC(u_mood, coarse_u_mood);
  (void) pbval_mood->ClearSend();
  (void) pbval_mood->ClearRecv();
  (void) pbval_mood->RecvAndUnpackCC(u_mood, coarse_u_mood);
  if (pm->multilevel) {
    pbval_mood->FillCoarseInBndryCC(u_mood, coarse_u_mood);
    pbval_mood->ProlongateCC(u_mood, coarse_u_mood);
  }
}

//----------------------------------------------------------------------------------------
//! \fn int Particles::MoodDemote()
//! \brief bump deposit_order_p by one wherever a particle's stencil touches a flagged
//! cell, and return the GLOBAL number of particles demoted this sweep.
//!
//! The stencil is evaluated in the particle's OWN block frame with the particle's CURRENT
//! kernel; it reaches at most ShapeHalf <= nghost cells outside, which the ghost fill has
//! made valid. For a coarse block whose cloud is represented on its fine sublevel at a
//! seam, testing the coarse-frame stencil covers a superset of the deposited region -- a
//! safe over-approximation.

int Particles::MoodDemote() {
  auto &indcs = pmy_pack->pmesh->mb_indcs;
  auto &size = pmy_pack->pmb->mb_size;
  int is = indcs.is, js = indcs.js, ks = indcs.ks;
  int ncell[3] = {indcs.nx1, indcs.nx2, indcs.nx3};
  int gids = pmy_pack->gids;
  int npart = nprtcl_thispack;
  auto &pi = prtcl_idata;
  auto &pr = prtcl_rdata;
  auto &flag = u_mood;
  auto &porder = deposit_order_p;
  int nlev = mood_nlevels;
  DepositShape h0 = mood_hier[0], h1 = mood_hier[1], h2 = mood_hier[2];

  int ndem = 0;
  if (npart > 0) {
    Kokkos::parallel_reduce("mood_demote", Kokkos::RangePolicy<>(DevExeSpace(), 0, npart),
      KOKKOS_LAMBDA(const int p, int &cnt) {
        int lev = porder(p);
        if (lev >= nlev-1) {return;}            // already on the parachute
        DepositShape sh = (lev == 0) ? h0 : ((lev == 1) ? h1 : h2);
        int W = ShapeWidth(sh);
        int s0 = ShapeOffset(sh);
        int m = pi(PGID,p) - gids;
        const RegionSize &sz = size.d_view(m);
        Real x[3] = {pr(IPX,p), pr(IPY,p), pr(IPZ,p)};
        Real xmn[3] = {sz.x1min, sz.x2min, sz.x3min};
        Real xmx[3] = {sz.x1max, sz.x2max, sz.x3max};
        int idx[3];
        for (int d=0; d<3; ++d) {
          idx[d] = LeftCenterIndex(x[d], ncell[d], xmn[d], xmx[d]);
        }
        bool hit = false;
        for (int sk=0; sk<W && !hit; ++sk) {
          int ck = ks + idx[2] + s0 + sk;
          for (int sj=0; sj<W && !hit; ++sj) {
            int cj = js + idx[1] + s0 + sj;
            for (int si=0; si<W && !hit; ++si) {
              int ci = is + idx[0] + s0 + si;
              if (flag(m,0,ck,cj,ci) > kMoodFlagged) {hit = true;}
            }
          }
        }
        if (hit) {
          porder(p) = lev + 1;
          ++cnt;
        }
      }, Kokkos::Sum<int>(ndem));
  }
#if MPI_PARALLEL_ENABLED
  MPI_Allreduce(MPI_IN_PLACE, &ndem, 1, MPI_INT, MPI_SUM, pbval_part->mpi_comm_part);
#endif
  return ndem;
}

//----------------------------------------------------------------------------------------
//! \fn void Particles::MoodStampRecords()
//! \brief copy the per-particle hierarchy level onto every record this rank generated
//! (self records, same-rank images and the staged cross-rank wire records). Records that
//! arrived over MPI carry src_p = -1 and are refreshed instead by
//! ParticlesBoundaryValues::RefreshTmunuImageOrders().

void Particles::MoodStampRecords() {
  auto &porder = deposit_order_p;
  int nimg = nimages_thispack;
  if (nimg > 0) {
    auto &img = tmunu_images;
    par_for("mood_stamp_local", DevExeSpace(), 0, (nimg-1), KOKKOS_LAMBDA(const int g) {
      int sp = img.d_view(g).src_p;
      if (sp >= 0) {img.d_view(g).order = porder(sp);}
    });
  }
  int nsend = nimg_send_thispack;
  if (nsend > 0) {
    auto &snd = tmunu_img_send;
    par_for("mood_stamp_send", DevExeSpace(), 0, (nsend-1), KOKKOS_LAMBDA(const int n) {
      int sp = snd.d_view(n).src_p;
      if (sp >= 0) {snd.d_view(n).order = porder(sp);}
    });
  }
}

//----------------------------------------------------------------------------------------
//! \fn void Particles::MoodReport()
//! \brief per-cycle census of the fallback: how many particles ended on each level, how
//! many cells were still inadmissible before and after the cascade, and a radial
//! histogram
//! of the demoted particles (the SPATIAL fallback frequency -- the paper reports no such
//! statistics at all). Appends one row to <basename>.mood.csv on rank 0.

void Particles::MoodReport(int ncycle, Real time, int nsweep, int nbad0, int nbad1) {
  int npart = nprtcl_thispack;
  auto &porder = deposit_order_p;
  auto &pr = prtcl_rdata;
  auto &ct = mood_level_ct;
  auto &rad = mood_radial;
  int nbin = mood_nbin;
  Real rmax = mood_rmax;
  Real cx = mood_center[0], cy = mood_center[1], cz = mood_center[2];

  Kokkos::deep_copy(ct, 0);
  if (nbin > 0) {Kokkos::deep_copy(rad, 0);}
  if (npart > 0) {
    par_for("mood_census", DevExeSpace(), 0, (npart-1), KOKKOS_LAMBDA(const int p) {
      int lev = porder(p);
      if (lev < 0) {lev = 0;}
      if (lev > 2) {lev = 2;}
      Kokkos::atomic_add(&ct(lev), 1);
      if (nbin > 0 && rmax > 0.0) {
        Real dx = pr(IPX,p) - cx, dy = pr(IPY,p) - cy, dz = pr(IPZ,p) - cz;
        Real r = sqrt(dx*dx + dy*dy + dz*dz);
        int b = static_cast<int>((r/rmax)*static_cast<Real>(nbin));
        if (b >= 0 && b < nbin) {Kokkos::atomic_add(&rad(lev*nbin + b), 1);}
      }
    });
  }
  auto hct = Kokkos::create_mirror_view(ct);
  Kokkos::deep_copy(hct, ct);
  auto hcr = Kokkos::create_mirror_view(mood_ncell);
  Kokkos::deep_copy(hcr, mood_ncell);
  std::vector<int> hrad;
  if (nbin > 0) {
    auto hr = Kokkos::create_mirror_view(rad);
    Kokkos::deep_copy(hr, rad);
    hrad.assign(hr.data(), hr.data() + 3*nbin);
  }
#if MPI_PARALLEL_ENABLED
  MPI_Allreduce(MPI_IN_PLACE, hct.data(), 3, MPI_INT, MPI_SUM, pbval_part->mpi_comm_part);
  MPI_Allreduce(MPI_IN_PLACE, hcr.data(), 5, MPI_INT, MPI_SUM, pbval_part->mpi_comm_part);
  if (nbin > 0) {
    MPI_Allreduce(MPI_IN_PLACE, hrad.data(), 3*nbin, MPI_INT, MPI_SUM,
                  pbval_part->mpi_comm_part);
  }
#endif
  if (global_variable::my_rank != 0) {return;}

  FILE *fp = nullptr;
  if (!mood_log_open) {
    // A restart re-enters this function with mood_log_open == false. Opening "w" would
    // truncate the census written by the previous segment, so write a header only when
    // the file does not exist yet (or is empty); otherwise append and keep the history.
    bool fresh = true;
    {
      FILE *probe = std::fopen(mood_log_fname.c_str(), "r");
      if (probe != nullptr) {
        std::fseek(probe, 0, SEEK_END);
        fresh = (std::ftell(probe) <= 0);
        std::fclose(probe);
      }
    }
    fp = std::fopen(mood_log_fname.c_str(), fresh ? "w" : "a");
    if (fp != nullptr && !fresh) {
      std::fprintf(fp, "# --- restart: census resumes here ---\n");
      mood_log_open = true;
    }
    if (fp != nullptr && fresh) {
      std::fprintf(fp, "# MOOD fallback census. levels are hierarchy"
                       " positions of\n");
      std::fprintf(fp, "# <particles> deposit_shape; 0 = highest order, last = M4.\n");
      std::fprintf(fp, "# radial histogram: nbin=%d rmax=%.17g centre=(%.17g,%.17g,%.17g)"
                       "\n", nbin, mood_rmax, mood_center[0], mood_center[1],
                   mood_center[2]);
      std::fprintf(fp, "# crit_* are the LAST sweep's per-criterion cell counts:\n");
      std::fprintf(fp, "#   crit_E = E < 0 ; crit_Saa = S_aa < 0 ;\n");
      std::fprintf(fp, "#   crit_ESaa = E*S_aa - S_a^2 < 0 ; crit_SS = S_aa*S_bb -"
                       " S_ab^2 < 0 ; crit_nan\n");
      std::fprintf(fp, "cycle,time,nsweep,n_lev0,n_lev1,n_lev2,nbad_first,nbad_final,"
                       "crit_E,crit_Saa,crit_ESaa,crit_SS,crit_nan");
      for (int l=0; l<3; ++l) {
        for (int b=0; b<nbin; ++b) {std::fprintf(fp, ",h%d_%d", l, b);}
      }
      std::fprintf(fp, "\n");
      mood_log_open = true;
    }
  } else {
    fp = std::fopen(mood_log_fname.c_str(), "a");
  }
  if (fp == nullptr) {return;}
  std::fprintf(fp, "%d,%.17g,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d", ncycle, time, nsweep,
               hct(0), hct(1), hct(2), nbad0, nbad1,
               hcr(0), hcr(1), hcr(2), hcr(3), hcr(4));
  for (int l=0; l<3; ++l) {
    for (int b=0; b<nbin; ++b) {std::fprintf(fp, ",%d", hrad[l*nbin + b]);}
  }
  std::fprintf(fp, "\n");
  std::fclose(fp);
}

} // namespace particles
